#!/bin/bash

die(){
    echo $* 1>&2
    exit 1
}

[ $# -lt 2 ] && die "Usage: $0 repo package [versions]"

repo=$1
package=$2
shift; shift;
versions=$@

echo "versions $versions"

repoURL=$(yq -r '.repositories[] | select(.name=="'$repo'") | .url' ~/.helm/repository/repositories.yaml)
[ "$repoURL" ] || die "Repository $repo not found"

chartURL=$repoURL/api/charts/$package

[ "$versions" ] || versions=$(curl -s $chartURL| jq -r .[].version) || die "No versions found for $package"

for version in $versions; do
    curl -sX DELETE ${chartURL}/$version
done
