#!/bin/bash

[ "$1" == "-d" ] && { debug=echo; shift; }

version=$1
outdir=/tmp
repo=cli/cli
arch=amd64

if [ -e /etc/apt/sources.list ]; then
    format=deb
elif [ -e /etc/redhat-release ]; then
    format=rpm
fi


[ "$version" ] || version=$(curl -sI https://github.com/${repo}/releases/latest| awk -F/ '/^location/{print $NF}' | tr -d v\\r)
filename=gh_${version}_linux_${arch}.${format}

$debug curl -sL https://github.com/${repo}/releases/download/v${version}/${filename} -o ${outdir}/${filename}

case $format in
    deb) command="dpkg -i" ;;
    rpm) command="rpm -Uvh" ;;
esac

$debug sudo ${command} ${outdir}/${filename}
