#!/bin/bash

KUBECONFIG_TEMPLATE='
kind: Config
apiVersion: v1
preferences: {}
clusters:
- cluster:
    certificate-authority-data: ${KUBE_CA}
    server: ${KUBE_APISERVER}
  name: kubernetes
users:
- name: kubernetes
  user:
    client-certificate-data: ${KUBE_CRT}
    client-key-data: ${KUBE_KEY}
contexts:
- context:
    cluster: kubernetes
    user: kubernetes
  name: kubernetes
current-context: kubernetes
'

usage(){
  cat >&2 << EOF
  kube-create-kubeconfig

  Usage:
    $0 apiserver ca_file user.crt user.key
EOF
}

b64enc(){
   base64 -w0 $1 || exit 1
}

[ $# -ne 4 ] && usage && exit 1

export KUBE_APISERVER=$1
CA=$2
CRT=$3
KEY=$4

export KUBE_CA=$(b64enc $CA)
export KUBE_CRT=$(b64enc $CRT)
export KUBE_KEY=$(b64enc $KEY)

echo "$KUBECONFIG_TEMPLATE" | envsubst
