#!/bin/bash
# Tmux notifier for taskwarrior
# Add to your status line with
# set-option -g status-left "#(path_to_this_file)"

# Default status
state=" "

# New tasks are marked with tags +n -w
tags_new="+n -w"
tasks_new="#[bg=red]#[fg=brightwhite] "
# Updated tasks are marked with tags +u -w
tags_upd="+u -w"
tasks_upd="#[bg=color172] "
tasks_error="#[bg=red]#[fg=brightwhite]E"

lockfile=$HOME/.task/lockedtask

if [[ -f $HOME/.task/lockedtask ]]; then
    state="$tasks_error"
    # If lockfile is older than 10 minutes, autoclean
    find "$lockfile" -mmin +10 | grep -q "$lockfile" && t rmlock
elif task $tags_new &>/dev/null; then
    state="$tasks_new"
elif task $tags_upd &>/dev/null; then
    state="$tasks_upd"
fi

echo "$state"
